############################################
## 	Makefile for sensors devices 												
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_SENSORS_MPU6880)			+= mpu6880.o
