obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o

obj-$(CONFIG_MPU_SENSORS_MPU6050B1)	+= mpu6050/
obj-$(CONFIG_YL_SENSORS_ALSPROX)	+= alsprox/
obj-$(CONFIG_YL_SENSORS_COMPASS)	+= compass/
obj-$(CONFIG_YL_SENSORS_FINGERPRINT)	+= fingerprint/
obj-$(CONFIG_YL_SENSORS_GESTURE)	+= gesture/
obj-$(CONFIG_YL_SENSORS_GSENSOR)	+= accel/
obj-$(CONFIG_YL_SENSORS_HALL)		+= hall/
obj-$(CONFIG_YL_SENSORS_HUMITURE)	+= humiture/
obj-$(CONFIG_YL_SENSORS_MPU6880)	+= mpu6880/
obj-$(CONFIG_YL_SENSORS_PARAMS)		+= sensparams/
obj-$(CONFIG_YL_SENSORS_PRESSURE)	+= pressure/
obj-$(CONFIG_YL_SENSORS_SENSORHUB)	+= sensorhub/
