obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o

obj-$(CONFIG_YL_SENSORS_HALL)	+= hall/
obj-$(CONFIG_YL_SENSORS_MPU6880)	+= mpu6880/
obj-$(CONFIG_YL_SENSORS_PARAMS)	+= sensparams/
