############################################
## 	Makefile for sensors devices 												
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_TXC_PA12200001)			+= pa12200001.o
