############################################
## 	Makefile for sensors devices 			
## 	Author:LongJiang 									
## 	Date:2013-09-30									
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_LTR559_ALSPROX)		+= ltr559.o
