############################################
## 	Makefile for acc sensors devices 			
## 	Author:LongJiang 									
## 	Date:2013-09-13 									
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_BMA2x2_GSENSOR)	+= bma2x2/
obj-$(CONFIG_YL_KIONIX_GSENSOR)	+= kionix/
obj-$(CONFIG_YL_LIS3DH_GSENSOR)	+= lis3dh/
