############################################
## 	Makefile for accel sensors devices 			
## 	Author:LongJiang 									
## 	Date:2013-09-13 									
############################################

#
# Makefile for miscellaneous I2C chip drivers.
#
# Do not add new drivers to this directory! It is DEPRECATED.
#
# Device drivers are better grouped according to the functionality they
# implement rather than to the bus they are connected to. In particular:
# * Hardware monitoring chip drivers go to drivers/hwmon
# * RTC chip drivers go to drivers/rtc
# * I/O expander drivers go to drivers/gpio
#

obj-$(CONFIG_YL_BMA2x2_GSENSOR)	+= bma2x2.o
