############################################
## 	Makefile for sensors devices 			
## 	Author:LongJiang 									
## 	Date:2013-09-25 									
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_LIS3DH_GSENSOR)	+= lis3dh_acc.o
