#gt915 touchpanel driver

obj-$(CONFIG_TOUCHSCREEN_GT9XX_HQ_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_TOUCHSCREEN_GT9XX_HQ_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_TOUCHSCREEN_GT9XX_HQ_DEBUG)	+= goodix_tool.o
