#gt915 touchpanel driver

obj-$(CONFIG_TOUCHSCREEN_HQ_GT9XX_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_TOUCHSCREEN_HQ_GT9XX_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_TOUCHSCREEN_HQ_GT9XX_DEBUG)	+= goodix_tool.o
